# SAM CLI Configuration File
# Run 'sam deploy --guided' to generate custom values

version = 0.1

[default.global.parameters]
stack_name = "snowpark-widf-lambda-dev"
region = "us-west-2"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
resolve_s3 = true

[dev]
[dev.deploy.parameters]
stack_name = "snowpark-widf-lambda-dev"
parameter_overrides = "Environment=dev"

[prod]
[prod.deploy.parameters]
stack_name = "snowpark-widf-lambda-prod"
parameter_overrides = "Environment=prod"
